- name: apps
  hosts: all
  vars:
    state: present
    apps:
      - psexec
      - firefox
      - openssh
      - googlechrome
  tasks:
    - name: ensure chocolatey present
      win_chocolatey:
        name: chocolatey

    - name: configure internal repo
      win_chocolatey_source:
        name: internal repo
        state: present
        source: '\\{{ chocolatey_repo_server | default(hostvars["wintarget4"].ansible_host) }}\repo'
        priority: 1
      when: state == 'present'

    - name: ensure apps are {{ state }}
      win_chocolatey:
        name: "{{ apps }}"
        state: "{{ state }}"
        ignore_checksums: true